[package]
name = "link"
version = "0.1.0"
edition = "2021"


[dependencies]
thiserror = { version="1.0.40", optional = true }
tokio =     { version="1.28.0", optional = true }

[features]
default = []
errors = ["dep:thiserror"]
tokio = ["dep:tokio"]
